test: fix failure (#2)
$ bundle exec rake test
    /home/daipom/.rbenv/versions/3.2.2/bin/ruby -w -I"lib:lib:test" /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb "test/plugin/test_in_fluent_package_update_notifier.rb"
    /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:36:in `block in included': undefined method `setup' for Test::Unit::TestCase:Class (NoMethodError)

                setup :before => :prepend
                ^^^^^
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:35:in `module_eval'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:35:in `included'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:110:in `include'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:110:in `<class:TestCase>'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:109:in `<module:Unit>'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/test-unit-rr-1.0.5/lib/test/unit/rr.rb:24:in `<top (required)>'
    	from <internal:/home/daipom/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
    	from <internal:/home/daipom/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
    	from /home/daipom/work/fluentd/plugins/fluent-plugin-fluent-package-update-notifier/test/helper.rb:2:in `<top (required)>'
    	from <internal:/home/daipom/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
    	from <internal:/home/daipom/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
    	from /home/daipom/work/fluentd/plugins/fluent-plugin-fluent-package-update-notifier/test/plugin/test_in_fluent_package_update_notifier.rb:1:in `<top (required)>'
    	from <internal:/home/daipom/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
    	from <internal:/home/daipom/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21:in `block in <main>'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `select'
    	from /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `<main>'
    rake aborted!

Signed-off-by: Daijiro Fukuda <fukuda@clear-code.com>